# Site settings
title: Alveena Nadeem
description: Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alveena Nadeem
user_description: hire me
email: alveenanadeem2103@gmail.com
# instagram: 
instagram_username: alveena210
#facebook_username: mauricio.urraco
linkedin_username: alveena
github_username:  alvs210
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

